import random

name = input("what is your name? ")
num = random.randint(1,100)
guesses_left = 7 #this is for how many guesses they have
x = num - random.randint(1,5)  #this is the min value for the range of the hint the computer can give
y = num + random.randint(1,5)  #this is the max value for the range of the hint the computer can give
start = input("Are you ready if so click start or if not click exit: ") #This is confirmation that the user wants to continue(optional)
if start == "start":
    print("goodluck...")
if start == "exit":
    print("noooo")


print("you have: " + str(guesses_left) + " guesses left") #this shows their intial guess amount
while guesses_left > 0: # the while loop puts it in a loop while the number of guesses is more than zero
    guess = int((input("what number do you guess? "))) 
    if guess == num:
        print("Congratulations " +  name  + " you entered correct!")
        exit()
    if guess > num: # this means the number generated by the computer is less than the guess of the user
        print("your guess is high try again")
        guesses_left -= 1 # this decreases the number of chances they have by one
        print("I will give you a hint, the number is between " + str(x) + " and " + str(y)) # this shows what range the number generated by the computer is in
        print("you have: " + str(guesses_left) + " guesses left") # this shows how many guesses they have left
        print("try again")
    if guess < num: # this is when the user input is less than the number generated
        print("you are low try again")
        guesses_left -= 1
        print("I will give you a hint, the number is between " + str(x) + " and " + str(y))
        print("you have: " + str(guesses_left) + " guesses left")
        print("try again")
else: # once they run out of guesses the progam ends
    print("you lose")
    exit()
